# -*- coding: utf-8 -*-
"""iris flower classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ejc0sV8pKU5YiPSLwgmBqaG55GiPdAXT
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

df=pd.read_csv('/content/iris_data.csv')

df.head()

df['Species'].value_counts()

df.shape

df.isnull().sum()

df=df.drop(columns='Id',axis=1)

x=df.drop(columns='Species',axis=1)
y=df['Species']

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

"""model 1 - logistic regression"""

logistic_model=LogisticRegression()
logistic_model.fit(x_train,y_train)

from sklearn.metrics import accuracy_score

pred_test=logistic_model.predict(x_test)
accuracy_test=accuracy_score(y_test,pred_test)
print(accuracy_test)

from sklearn.metrics import f1_score

f1_test=f1_score(y_test,pred_test,average='weighted')
print(f1_test)

"""model 2 - knn"""

knn_model=KNeighborsClassifier(n_neighbors=5)
knn_model.fit(x_train,y_train)

accuracy_test=accuracy_score(y_test,knn_model.predict(x_test))
print(accuracy_test)

f1_test=f1_score(y_test,knn_model.predict(x_test),average='weighted')
print(f1_test)

"""model 3 - random forest"""

random_forest_model=RandomForestClassifier(n_estimators=100)
random_forest_model.fit(x_train,y_train)

accuracy_test=accuracy_score(y_test,random_forest_model.predict(x_test))
print(accuracy_test)

import pickle

filename='iris_model_logistic.sav'
pickle.dump(logistic_model,open(filename,'wb'))

filename='iris_model_knn.sav'
pickle.dump(knn_model,open(filename,'wb'))

filename='iris_model_random_forest.sav'
pickle.dump(random_forest_model,open(filename,'wb') )

df.describe()

